music_library = {
    "heer aasmani (from 'fighter')": "https://open.spotify.com/track/68hDecrVQCvVtzcYcvFMJX",
    "mauja hi mauja": "https://open.spotify.com/track/2iXVckhPy7tP0wV9DvlrjZ",
    "deja vu": "https://open.spotify.com/track/6HU7h9RYOaPRFeh0R3UeAr",
    "senorita": "https://open.spotify.com/track/3TAhWtQnpoL5Vl9VQPl9fU",
    "beedi": "https://open.spotify.com/track/2S6okBMEo9oWCbdWGrxth3",
    "tha kar ke": "https://open.spotify.com/track/5fwxHG57mYPY2f1NZ4qvCh",
    "chanakya": "https://open.spotify.com/track/4WZE6JnKn3jacgnaJOTF9T",
    "aaya re toofan (from 'chhaava')": "https://open.spotify.com/track/1E4eyxteUpXpwThyARHrVJ",
    "the roar (from 'chhaava')": "https://open.spotify.com/track/0R97OfArQkB9hOptu72NiV",
    "payal": "https://open.spotify.com/track/76ZWOhRRQzmb4xMoZzTjJ9",
    "beggin'": "https://open.spotify.com/track/3Wrjm47oTz2sjIgck11l5e",
    "why this kolaveri di? - the soup of love": "https://open.spotify.com/track/5AjYjRsiIPAKjRP182ocKB",
    "die with a smile": "https://open.spotify.com/track/2plbrEY59IikOBgBGLjaoe",
    "tony's mayhem": "https://open.spotify.com/track/3XT6lmQS1lfG9MO6dl3A2q",
    "jatt mehkma": "https://open.spotify.com/track/61R3DMR4U2n25qgX9ryciJ",
    "this party getting hot": "https://open.spotify.com/track/1jCsVnVmKT0FaHHldkMtOa",
    "munni badnaam": "https://open.spotify.com/track/6fORBVECjNDJ1gdq5uuoAz",
    "millionaire": "https://open.spotify.com/track/78BWCd70D1X6LMkDZm1UoF",
    "khoobsurat (from 'stree 2')": "https://open.spotify.com/track/1o8YPl0hyGbpRcHplXNvsm",
    "aayi nai (from 'stree 2')": "https://open.spotify.com/track/1mQUEvGR7Sbt2OCz2gFrdx",
    "big dawgs": "https://open.spotify.com/track/0OA00aPt3BV10qeMIs3meW",
    "mujhko yaad sataye teri": "https://open.spotify.com/track/2KQaNLCXDauWnNuVr6tOi2",
    "chinta ta ta chita chita": "https://open.spotify.com/track/0t4OUMPCxSFbUqcyyrojn5",
    "thumkeshwari": "https://open.spotify.com/track/6cI3I2flP8qvnLLgvrXWg0",
    "tumse milke dil ka": "https://open.spotify.com/track/1ax8ZuwRVkSdzzsIqyCNWQ",
    "tera hone laga hoon": "https://open.spotify.com/track/0dLbrlAVPPjpPqnYfmJsWk",
    "uff teri adaa": "https://open.spotify.com/track/0og9wKFGgFFNQnrBe7eisG",
    "ud-daa punjab": "https://open.spotify.com/track/7o65z7yxlOfbAiDxq9WZBy",
    "fanaa": "https://open.spotify.com/track/2GAfZQRZCr5OyuZbYjMqb9",
    "zara sa (from 'jannat')": "https://open.spotify.com/track/0bNtRfrX1bNNiI2P4cCXU6",
    "phir kabhi (from 'm.s.dhoni - the untold story')": "https://open.spotify.com/track/77gskLti3ilCnuwlDq0m8j",
    "jab tak": "https://open.spotify.com/track/1im9BMeeKze7rkBPIEpCUr",
    "guzarish (from 'ghajini')": "https://open.spotify.com/track/39bHz64P8EIGXnoPfpYnUE",
    "character dheela": "https://open.spotify.com/track/1r4oikmMdZZiGHkPA4hSoe",
    "pee loon": "https://open.spotify.com/track/52itZ0w0CydihB2JCZEIft",
    "tum hi ho bandhu": "https://open.spotify.com/track/7H3mfOvtPNA8YDF3EdKy0L",
    "main rang sharbaton ka": "https://open.spotify.com/track/1yYM7dY6wSJFp5qmxPRLu1",
    "mast magan": "https://open.spotify.com/track/3uL1IBFhg52VcQqOwAG01E",
    "ajab si": "https://open.spotify.com/track/5FXMRdJjKq1BIX4e8Eg9mK",
    "ye tune kya kiya": "https://open.spotify.com/track/2cPUB8EOT6AfJ8oxhyoNXL",
    "tu jaane na": "https://open.spotify.com/track/4iFPsNzNV7V9KJgcOX7TEO",
    "locha-e-ulfat": "https://open.spotify.com/track/3V3QbgrOZKtFv5MXzAAdZr",
    "kabhi kabhi aditi": "https://open.spotify.com/track/3APdIdF8H0jsxSuGOqXedS",
    "iktara": "https://open.spotify.com/track/3jtKSUiVDowKNBqVQbWaig",
    "tumhe jo maine dekha": "https://open.spotify.com/track/0pPGUL7171TRGgI6wyP8wP",
    "humko pyar hua": "https://open.spotify.com/track/4cltuh2RNH0LyZY9I8Vi08",
    "bulleya": "https://open.spotify.com/track/3tgdOveYac7YMEAQD9sGLf",
    "mirchi": "https://open.spotify.com/track/5KkCsYIgMK5H7Ih31Dnd2Q",
    "coca cola (from 'luka chuppi')": "https://open.spotify.com/track/352wEkChkiClswqwDoM0nj",
    "badri ki dulhania (title track)": "https://open.spotify.com/track/2xbvLQBFW7E9232BwMBljb",
    "main tera boyfriend (from 'raabta')": "https://open.spotify.com/track/5VAkPCJTE6tbyReo9J4IQj",
    "aa toh sahi": "https://open.spotify.com/track/6m41vTK0NgOSEimRMydDtb",
    "the naari naari song (from 'made in china')": "https://open.spotify.com/track/0VhKdIMXZ3INkyDoIyPy5l",
    "chalti hai kya 9 se 12": "https://open.spotify.com/track/0tCw2PeUxWK31YyiiZuYpZ",
    "slow motion (from 'bharat')": "https://open.spotify.com/track/7yEuRloGyxyu1KaWBTPP1Z",
    "milegi milegi (from 'stree')": "https://open.spotify.com/track/52uiJsA4FrtAZlgqxCJwJI",
    "leke prabhu ka naam (from 'tiger 3')": "https://open.spotify.com/track/66v97IvccVkHt40FIOq1LH",
    "swag se swagat": "https://open.spotify.com/track/2AjGLmuZK1fu21n1IpB9RU",
    "kamariya": "https://open.spotify.com/track/5HJvDTnAaDWqhsE841I1QR",
    "the disco song": "https://open.spotify.com/track/3UaP2PQwhA31keZXt7oPLA",
    "dilliwaali girlfriend": "https://open.spotify.com/track/3W1XPf7mvuQcWQB7U7MbTM",
    "afghan jalebi (film version)": "https://open.spotify.com/track/1rEVydQSe04NJUqyyEyeEq",
    "hookah bar": "https://open.spotify.com/track/4AoQVhME8Ko6LNm4lV2wwQ",
    "jai jai shivshankar (from 'war')": "https://open.spotify.com/track/6lfSsCL894Qw15xbt7cSUy",
    "nashe si chadh gayi": "https://open.spotify.com/track/0biCSADTAblvLTLtJz4pXO",
    "subha hone na de": "https://open.spotify.com/track/6WediUhXDfm8FR3wlM0r3G",
    "ghungroo (from 'war')": "https://open.spotify.com/track/0WdbnNKO0Jt4BZACSDQh44",
    "maston ka jhund": "https://open.spotify.com/track/3lSa2IIHfPmusFdvxFh9yE",
    "aaoge tum kabhi": "https://open.spotify.com/track/5ivRSlOhVIXN2QMzqgsX0s",
    "laapata": "https://open.spotify.com/track/3G2I8KB7bTWmvE1tHSlMHg",
    "de taali": "https://open.spotify.com/track/4elIi3mFO5d4GZeMUTpR6S",
    "the breakup song": "https://open.spotify.com/track/5FihcmME7NlwW8KbYOaHVH",
    "saturday saturday": "https://open.spotify.com/track/1m8n1KC9QMNF52M562qZhX",
    "yaar naa miley (from 'kick')": "https://open.spotify.com/track/0qzuXwxORXTwSsBU2aJGj5",
    "phir kabhi": "https://open.spotify.com/track/4jk4CaqBMBbMZhf3PuR1ai",
    "kamariya": "https://open.spotify.com/track/5cjVsWqIkBQC7acTRhL0RO",
    "daru badnaam": "https://open.spotify.com/track/2TzyJEUfWHGRsk3r6Emvbk",
    "khada hu aaj bhi wahi": "https://open.spotify.com/track/1XAHGlDR1yQArjJA5E116e",
    "angry": "https://open.spotify.com/track/5l9uFNSfjC23A0eMDJJKkY",
    "leo das entry (from 'leo')": "https://open.spotify.com/track/2r0ROhr7pRN4MXDMT1fEmd",
    "baadshah o baadshah": "https://open.spotify.com/track/57V7Fo4iocHEMJcf7Upt0M",
    "bhaag d.k. bose, aandhi aayi": "https://open.spotify.com/track/1sxh0eqIb8ulYypPuq6ZRu",
    "mere samnewali khidki mein": "https://open.spotify.com/track/5ZMuv6ESQmOHfXrm8FFncr",
    "aankhein khuli": "https://open.spotify.com/track/16XEVyPh5NT31CAAqPbxQF",
    "kar gayi chull": "https://open.spotify.com/track/3fPgIknlkDWXs1l2noKZbp",
    "i hate luv storys": "https://open.spotify.com/track/4zUPL2OPTO3hgNhjaA1Rjn",
    "chhote chhote peg": "https://open.spotify.com/track/3AQrBSjowqCFu2jiFFuGsv",
    "illuminati - from 'aavesham'": "https://open.spotify.com/track/1kFNFsAZ4iZy4vjBEtT12I",
    "mast kalander": "https://open.spotify.com/track/6alNZoLuClM6yFv3GnRANk",
    "one bottle down": "https://open.spotify.com/track/3hVc5y5mbcIEPADRGGGru9",
    "dope shope": "https://open.spotify.com/track/3pVXZ04pu8zYaiAHCrh6PV",
    "party on my mind": "https://open.spotify.com/track/5Rn1DPzSzUktbhuNDDJocS",
    "skyfall": "https://open.spotify.com/track/6VObnIkLVruX4UVyxWhlqm",
    "badtameez dil": "https://open.spotify.com/track/4eu27jAU2bbnyHUC3G75U8",
    "saturday saturday": "https://open.spotify.com/track/7MvQQGqYE4r0ucTarmI2Gr",
    "chaar botal vodka (from 'ragini mms 2')": "https://open.spotify.com/track/0QHEWicUbdyWuHsMcVd1Ka",
    "kaayi": "https://open.spotify.com/track/4POXo4IBs74MRjBB5NctbP",
    "give me some sunshine": "https://open.spotify.com/track/1Qt0OGUUPibpmk1FpFQ43m",
    "joota japani": "https://open.spotify.com/track/3G0gdqt4LTreFwBYaymUhp",
    "psycho saiyaan (from 'saaho')": "https://open.spotify.com/track/3ZjMdVOWxQ53FKrmkgCv95",
    "urvashi": "https://open.spotify.com/track/342pJxy678kgQrZXCL9RG7",
    "high heels te nachche (from 'ki & ka') (feat. jaz dhami, aditi singh sharma)": "https://open.spotify.com/track/0MAL4lkJiJgCwGdO0Q264f",
    "jagga jiteya": "https://open.spotify.com/track/1rQ1Quwa40g2D5qiDszzPg",
    "party all night (from 'boss')": "https://open.spotify.com/track/1bHBYJjUYYbUnwKYCFxV1F",
    "not ramaiya vastavaiya": "https://open.spotify.com/track/5inzjqKe05zP1eInEO8O1i",
    "chak lein de (from 'chandni chowk to china')": "https://open.spotify.com/track/3E0D36S3MKA9e3f8yCOFR3",
    "besharam rang (from 'pathaan')": "https://open.spotify.com/track/0CtZpaOhtzvLV3FfcsVpQo",
    "long drive": "https://open.spotify.com/track/0sSapNABKrGwgaMhn0p8uL",
    "lonely": "https://open.spotify.com/track/0koCvqji2k9Me2QJSjCzds",
    "challa": "https://open.spotify.com/track/7GjfRKsWOScFTXoX8s0Ln4",
    "thee thalapathy (from 'varisu')": "https://open.spotify.com/track/6TK7jseRCrogw9IzQYkw2h",
    "eyy bidda ye mera adda": "https://open.spotify.com/track/0jenJohxJTFQTuqi5Js0Dg",
    "paisa hai toh": "https://open.spotify.com/track/5kwldaZvtbiTmRYsmlyxAN",
    "raftaarein": "https://open.spotify.com/track/3pjZQfBShK7O01QvtQwmcg",
    "ratata (from 'leo')": "https://open.spotify.com/track/58clncAcNFhSh5ERdonnCp",
    "i'm scared (from 'leo')": "https://open.spotify.com/track/6vPFDbyzSYWAL7r3Waa7BZ",
    "villain yaaru (from 'leo')": "https://open.spotify.com/track/6p8DwAh6wJ7S6jmpyYlBYp",
    "lokiverse 2.0": "https://open.spotify.com/track/5OxVOeYmIzelfupJtq1X6G",
    "badass (from \"leo\")": "https://open.spotify.com/track/32qnBgfzURbwNayQIEB5W5",
    "naa ready (from \"leo\")": "https://open.spotify.com/track/1B02UI29t3PTh3m98absaP",
    "bloody sweet (from \"leo\")": "https://open.spotify.com/track/4lCJO8QeKIkU2um1z5NBb9",
    "har funn maula (from \"koi jaane na\")": "https://open.spotify.com/track/3ayMReTwLoo6jAg7adDqyz",
    "jai hanuman gyan gun sagar (theme)": "https://open.spotify.com/track/2U5yM4bR3uFzHSc1H7KnUC",
    "haan yahan kadam kadam par x ek din pyar - srk x mc stan": "https://open.spotify.com/track/5aSAjzYimsv4c3oC4WCk8f",
    "hindu chalisa": "https://open.spotify.com/track/7vhaVFlG1xLJkDCzFjE0cO",
    "bharat ka baccha baccha x jai sri ram": "https://open.spotify.com/track/1vdptK3EqGe1aTbIvJxDyF",
    "संपूर्ण गीता mahabharat krishna rap kavi amit sharma": "https://open.spotify.com/track/6GJIM4xG6o30mqypi79kWH",
    "kalyug vs krishna": "https://open.spotify.com/track/4XXoT6JzIyYOmdn10zXCSU",
    "shri ram janki - remix": "https://open.spotify.com/track/6CekkIYPFWueGWTIBbpYAH",
    "ram doot": "https://open.spotify.com/track/5AZbpsrRJ5VxP2UNKlSPlq",
    "bharat ka baccha baccha": "https://open.spotify.com/track/3pdQSa3JBrYIuqJOJmFrxl",
    "babam bam lahari": "https://open.spotify.com/track/4QtBh2dBIPzbRDrwYmiELJ",
    "main hoon ghatothkach (child)": "https://open.spotify.com/track/4eGoKbelVEhhFjBn7dzAIm",
    "mahakal rap song _ deva aghori": "https://open.spotify.com/track/0VUuM2mW7v7y6qqTnblH4p",
    "saugandh mujhe iss mitti ki": "https://open.spotify.com/track/6FJZsvuxo1q8fwXWcZN6TX",
    "mahabharat story rap": "https://open.spotify.com/track/1ciQvemgE09P1oD9r2NmiZ",
    "the hanuman chalisa rap": "https://open.spotify.com/track/5fbC10uq63kWj2Begp4DeM",
    "garma garam siro 2.0": "https://open.spotify.com/track/0Wn1dtM9DOeMCT9RzzeLdX",
    "nashik dhol 2": "https://open.spotify.com/track/20zbLZ6Ym2CPP2bHJduza7",
    "nashik dhol": "https://open.spotify.com/track/11Gp1cv6QbGRRMYWtPaEBM",
    "khalasi | coke studio bharat": "https://open.spotify.com/track/5LSAafg2oH9YPgf3EG17iw",
    "kanudo nonstop (dj hari surat)": "https://open.spotify.com/track/129sACo6eMJzQr1VxbsLBy",
    "garma garam siro": "https://open.spotify.com/track/6V1IVIbvwNt0F2Ct430EfM",
    "jawan title track": "https://open.spotify.com/track/0lZhDg6xVjHLwL5zYd6nkL",
    "hukum - thalaivar alappara - tamil (from \"jailer\")": "https://open.spotify.com/track/3pDbPKZHrpHAWcJVMsrNwA",
    "alappara theme - instrumental": "https://open.spotify.com/track/4ui3hCbu9ERDqVMENogH3e",
    "tiger zinda hai theme - teaser": "https://open.spotify.com/track/6T02nAjutjkqmtmtjnOKME",
    "har fun maula x money in the grave": "https://open.spotify.com/track/6crpq21x9cOUKGSPmEh5Lp",
    "gangsta's paradise": "https://open.spotify.com/track/1DIXPcTDzTj8ZMHt3PDt8p",
    "immigrant song - remaster": "https://open.spotify.com/track/78lgmZwycJ3nzsdgmPPGNx",
    "bam lahiri": "https://open.spotify.com/track/6pf5fo5TRyimTOKSTZIP2t",
    "yadav brand 2": "https://open.spotify.com/track/4JvziZ2kQsbzfvRQtpYfmJ",
    "yadav brand 2 (slowed reverb)": "https://open.spotify.com/track/2rZ28NWX3NG2BbWc38JC1j",
    "naan naan": "https://open.spotify.com/track/3MBUQcMPekDVtn5mZ6Nv7c",
    "grind": "https://open.spotify.com/track/16xg7UwH9hbs96vCD8k6bC",
    "brothers anthem": "https://open.spotify.com/track/3uZiNvBNQldjl4OJiKsuxe",
    "kaleshi chori": "https://open.spotify.com/track/6FrihRowEuYfNehH0zcx0e",
    "dilli_s swag": "https://open.spotify.com/track/7z14jau7LGKM807sqQewIN",
    "the king is back (theme)": "https://open.spotify.com/track/31P81AYZ6BXBvY3QO9aq3r",
    "kabir's theme - instrumental": "https://open.spotify.com/track/3zdJrbhHGkcE4j2gYzLxbh",
    "khalid's theme - instrumental": "https://open.spotify.com/track/52MTLNmNS5afDkihIu0rSi",
    "tigers theme": "https://open.spotify.com/track/34TMYzSevBzOJkx5mEIb7D",
    "night is dark": "https://open.spotify.com/track/1VazemXN4V7m3JVvMYSd6g",
    "shankara re shankara (from \"tanhaji - the unsung warrior\")": "https://open.spotify.com/track/0KdtZvoOvUapwn6XK2LYMy",
    "prassthanam title song (8d audio)": "https://open.spotify.com/track/4PCDZHYFPdvolfLaBxFQyw",
    "mankatha theme music": "https://open.spotify.com/track/1A1YlVucS5hugYaeWXfCA8",
    "jhoome jo pathaan": "https://open.spotify.com/track/6FAYpZ4jve8vpvTwUvjK6H",
    "baby stop": "https://open.spotify.com/track/5wIKxAhAII20xChbjrocvS",
    "baby stop (extended version)": "https://open.spotify.com/track/2ylQeR6kbKA3uGTsdND9yK",
    "surviva (feat. yogi b & mali)": "https://open.spotify.com/track/0jvNc73pMCkyHTchaQu6NV",
    "satya": "https://open.spotify.com/track/1xSCr5uIndaHKFdO4s2V6B",
    "bajrang dal": "https://open.spotify.com/track/1HLIAR7YB9l0ialtHRWWbz",
    "war theme - instrumental": "https://open.spotify.com/track/1NU7wCHSRAOM9S4xk4CMQ0",
    "vaathi coming": "https://open.spotify.com/track/2BcPFQ7nrtUObgAs72xaac",
    "kalki bgm": "https://open.spotify.com/track/67rmDNTvwOGRWvx2EmO6TL",
    "mein": "https://open.spotify.com/track/7wpzsG1cuzHMt9sXA62W6n",
    "baazigar": "https://open.spotify.com/track/1T44wPr7LUlBY4vX6LlygG",
    "pungi": "https://open.spotify.com/track/4St20qfnH98z2CEY7Up5yn",
    "fairytale (slowed - house remix)": "https://open.spotify.com/track/0qEXE8VTE54aHLdMnUs9VV",
    "vardaan": "https://open.spotify.com/track/0MRg2bzlVhGQTi4ecu792k",
    "shoorveer": "https://open.spotify.com/track/6w6D4f9DbVxxWbnf5N9VdD",
    "aarambh": "https://open.spotify.com/track/1PZZtXR7nsNIyRcqd7UeiF",
    "get out of my way": "https://open.spotify.com/track/68Pjs9oWm9lDtWclMP18k4",
    "ak theme music - ready to rage": "https://open.spotify.com/track/232kZYrxOYqyMeBFwudXEM",
    "kaththi theme - instrumental": "https://open.spotify.com/track/5QpX7FGJ3A6otJSayn0GHM",
    "dub theri step": "https://open.spotify.com/track/3ZUAuDavYW0KrYf1Q3fBDP",
    "adheeraa (from \"cobra\")": "https://open.spotify.com/track/4381FmKZc1uT2zzhBiknH7",
    "lokiverse - background score": "https://open.spotify.com/track/209pScL6fUhISxcLWkB6rf",
    "bande (from \"vikram vedha\")": "https://open.spotify.com/track/2RRb2lLPLhImO97GVKE2dV",
    "once upon a time": "https://open.spotify.com/track/4wCy7erulqUfFQNVaZBD9b",
    "ghamand kar (from \"tanhaji - the unsung warrior\")": "https://open.spotify.com/track/4FcZBCb6dANhvsEnFlgJwG", 
    "jd intro - background score": "https://open.spotify.com/track/7KqmDr9lTjwXnX5krMIKiC",
    "the monster song": "https://open.spotify.com/track/0pFZ8npcNXuYd6ou9iNUl5",
    "rolex theme - background score": "https://open.spotify.com/track/3Vb8KkT6Ub5fFGPYJCJyLh",
    "vikram title track - hindi": "https://open.spotify.com/track/75uJJC9gnQepYBEmPLS0rI",
    "blue eyes": "https://open.spotify.com/track/7wW9scVNLYFLsmBb1yAUmS",
    "brown munde": "https://open.spotify.com/track/58f4twRnbZOOVUhMUpplJ4",
    "bing bing boo!": "https://open.spotify.com/track/3efEocziYjASsr8RojWERn",
    "satisfya": "https://open.spotify.com/track/6HGoVbCUr63SgU3TjxEVj6",
    "astronaut in the ocean": "https://open.spotify.com/track/3Ofmpyhv5UAQ70mENzB277",
    "ainsi bas la vida": "https://open.spotify.com/track/4lsOsGMzO1yCjGVucoWOZ1",
    "believer": "https://open.spotify.com/track/0pqnGHJpmpxLKifKRmU6WP",
    "neon blade": "https://open.spotify.com/track/0iUrxveyNUBfj0cqjYEijt",
    "naacho naacho": "https://open.spotify.com/track/208sMwgVcaFt2mT79Df1KG"
}
